import { Nunito_Sans } from 'next/font/google'
import './globals.css'
import MobileHeader from './components/MobileHeader'
import { Providers } from './providers'

const nunito = Nunito_Sans({
  subsets: ['latin'],
  weights: ['200', '400', '600', '800', '900']
})

export const metadata = {
  title: 'Loan App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.className} w-screen h-screen mx-auto container`}>
        <main>
          <Providers>
            <MobileHeader />
            {children}
          </Providers>
        </main>
      </body>
    </html>
  )
}
