import { Nunito_Sans } from 'next/font/google'
import './globals.css'
import MobileHeader from './components/MobileHeader'

const nunito = Nunito_Sans({
  subsets: ['latin'],
  weights: ['200', '400', '600', '800', '900']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunito.className} w-screen h-screen mx-auto container`}>
        <main className=''>
          <MobileHeader />
          {children}
        </main>
      </body>
    </html>
  )
}
